staging-settings:
  user-workflow:
    workflow-name: "risk-monitor-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

production-settings:
  user-workflow:
    workflow-name: "risk-monitor-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""

fixture-settings:
  user-workflow:
    workflow-name: "risk-monitor-fixture"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.fixture.json"
    secrets-path: ""

api-fail-settings:
  user-workflow:
    workflow-name: "risk-monitor-api-fail"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.api-fail.json"
    secrets-path: ""
